#!/usr/bin/env bash
set -euo pipefail

usage() {
    echo "Usage: $0 [--global | feature ...]"
    echo "Examples:"
    echo "  $0"
    echo "  $0 --global"
    echo "  $0 node npm-packages"
}

# Check for help argument
if [[ $# -gt 0 ]] && [[ "$1" == "-h" || "$1" == "--help" ]]; then
    usage
    exit 0
fi

# Parse command line arguments
global_scenarios_only=false
if [[ $# -eq 1 && "$1" == "--global" ]]; then
    global_scenarios_only=true
    features=()
elif [[ " $* " == *" --global "* ]]; then
    echo "Error: --global must be used on its own." >&2
    usage >&2
    exit 1
else
    features=("$@")
fi

# Generate a log filename
log_file=/tmp/devcontainer-features-test_$(date +%Y%m%d_%H%M%S).log

# Print which tests are being run
if [[ "${global_scenarios_only}" == "true" ]]; then
    echo "Running devcontainer features test scenarios for the \"_global\" test ..."
elif [[ ${#features[@]} -eq 0 ]]; then
    echo "Running devcontainer features test scenarios for all features and the \"_global\" test ..."
else
    echo "Running devcontainer features test scenarios for selected features: ${features[*]} ..."
fi

echo

# Prepare arguments for the devcontainer features test command
if [[ "${global_scenarios_only}" == "true" ]]; then
    args=(--global-scenarios-only)
else
    args=(--skip-autogenerated --skip-duplicated)
    if [[ ${#features[@]} -gt 0 ]]; then
        args+=(--features "${features[@]}")
    fi
fi

# Execute the devcontainer features test command
devcontainer features test "${args[@]}" >"${log_file}" 2>&1

# Print the test report section from the log file
sed -n '/TEST REPORT/,$p' "${log_file}"

echo

# Exit status
exit_status=0

# Check for errors and/or warnings in the log file
if grep -qE "^(❌|⚠️)" "${log_file}"; then
    echo "Test failures/warnings were detected."
    exit_status=1
fi

# Check for errors and/or warnings in docker output
echo "For detailed test execution logs, see \"${log_file}\"."

# Exit
exit "${exit_status}"
