#!/usr/bin/env bash
set -euo pipefail

usage() {
    echo "Usage: $0 [--log-file filename] [--global | feature ...]"
    echo "Examples:"
    echo "  $0"
    echo "  $0 --global"
    echo "  $0 node npm-packages"
    echo "  $0 --log-file /tmp/feature-tests.log node"
}

# Parse command line arguments
global_scenarios_only=false
log_file=""
features=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h | --help)
            usage
            exit 0
            ;;
        --global)
            global_scenarios_only=true
            shift
            ;;
        --log-file)
            if [[ $# -lt 2 || -z "$2" ]]; then
                echo "Error: --log-file requires a filename." >&2
                usage >&2
                exit 1
            fi
            log_file=$2
            shift 2
            ;;
        *)
            features+=("$1")
            shift
            ;;
    esac
done

if [[ "${global_scenarios_only}" == "true" && ${#features[@]} -gt 0 ]]; then
    echo "Error: --global cannot be used with feature names." >&2
    usage >&2
    exit 1
fi

# Generate the default log filename from the repository directory name
if [[ -z "${log_file}" ]]; then
    repository_root=$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)
    project_name=$(basename "${repository_root}")
    log_file=/tmp/${project_name}/devcontainer-features-test_$(date +%Y%m%d_%H%M%S).log
fi

# Create the log directory when needed
mkdir -p "$(dirname "${log_file}")"

# Print the log filename
echo "Test execution logs will be written to \"${log_file}\"."

# Print which tests are being run
if [[ "${global_scenarios_only}" == "true" ]]; then
    echo "Running devcontainer features test scenarios for the \"_global\" test."
elif [[ ${#features[@]} -eq 0 ]]; then
    echo "Running devcontainer features test scenarios for all features and the \"_global\" test."
else
    echo "Running devcontainer features test scenarios for selected features: ${features[*]}."
fi

echo

# Prepare arguments for the devcontainer features test command
if [[ "${global_scenarios_only}" == "true" ]]; then
    args=(--global-scenarios-only)
else
    args=(--skip-autogenerated --skip-duplicated)
    if [[ ${#features[@]} -gt 0 ]]; then
        args+=(--features "${features[@]}")
    fi
fi

# Print the command to execute
echo "Executing: devcontainer features test ${args[*]}"

echo

# Execute the devcontainer features test command
devcontainer features test "${args[@]}" >"${log_file}" 2>&1

# Print the test report section from the log file
sed -n '/TEST REPORT/,$p' "${log_file}"

# Exit status
exit_status=0

# Check for errors and/or warnings in the log file
if grep -qE "^(❌|⚠️)" "${log_file}"; then
    echo
    echo "Test failures/warnings were detected."
    exit_status=1
fi

# Exit
exit "${exit_status}"
